In [3]:
from PIL import Image
import numpy as np
import sys
import os
import csv

# default format can be changed as needed
def createFileList(myDir, format='.jpg'):
    fileList = []
    print(myDir)
    for root, dirs, files in os.walk(myDir, topdown=False):
        for name in files:
            if name.endswith(format):
                fullName = os.path.join(root, name)
                fileList.append(fullName)
    return fileList

# load the original image
myFileList = createFileList('../keras/deneme/patient_file') 

for file in myFileList:
    print(file)
    img_file = Image.open(file)
    # img_file.show()

    # get original image parameters...
    width, height = img_file.size
    format = img_file.format
    mode = img_file.mode

    # Make image Greyscale
    img_grey = img_file.convert('L')
    #img_grey.save('result.png')
    #img_grey.show()

    # Save Greyscale values
    value = np.asarray(img_grey.getdata(), dtype=np.int).reshape((img_grey.size[1], img_grey.size[0]))
    value = value.flatten()
    print(value)
    with open("KidneyDataset.csv", 'a',newline='') as f:
        writer = csv.writer(f)
        writer.writerow(value)

../keras/deneme/patient_file
../keras/deneme/patient_file\1677-6119-ibju-45-01-0187-gf01_resized_resized.jpg
[24 17 24 ... 55 32 41]
../keras/deneme/patient_file\220px-DoubleJ_resized_resized.jpg
[233  78  77 ... 107 106 107]
../keras/deneme/patient_file\4278196_c89acd8c9c_b_resized_resized.jpg
[ 87  94 110 ...  38  19  18]
../keras/deneme/patient_file\4678aabdc62f49518d21058d737489bc_resized_resized.jpg
[ 49  69  75 ... 121 116  92]
../keras/deneme/patient_file\a76b6ccbbad41ce47f83f5878f53085e-F_G_R2_resized_resized.jpg
[137 141 183 ... 171 160 144]
../keras/deneme/patient_file\alti_resized_resized.jpg
[208 211 213 ...  19  13   4]
../keras/deneme/patient_file\altmisalti_resized_resized.jpg
[ 4  4  4 ... 10 10  9]
../keras/deneme/patient_file\altmisbes_resized_resized.jpg
[30 25 19 ... 13 13 12]
../keras/deneme/patient_file\altmisbir_resized_resized.jpg
[  0   0   0 ... 106  76  49]
../keras/deneme/patient_file\altmisdokuz_resized_resized.jpg
[ 0  4  1 ... 40 32 16]
../keras/deneme/pa

../keras/deneme/patient_file\yetmisdokuz_resized_resized.jpg
[5 0 1 ... 2 2 2]
../keras/deneme/patient_file\yetmisdort_resized_resized.jpg
[25 58 10 ... 18  7  1]
../keras/deneme/patient_file\yetmisiki_resized_resized.jpg
[  0   3  62 ... 186 142  72]
../keras/deneme/patient_file\yetmissekiz_resized_resized.jpg
[1 1 1 ... 0 6 2]
../keras/deneme/patient_file\yetmisuc_resized_resized.jpg
[ 72 134 174 ...  42  20   0]
../keras/deneme/patient_file\yetmisyedi_resized_resized.jpg
[  0   0   0 ... 115 106 129]
../keras/deneme/patient_file\yetmis_resized_resized.jpg
[176 136 159 ...  75  49  40]
../keras/deneme/patient_file\yirmialti_resized_resized.jpg
[ 72 101 120 ...  42  30  26]
../keras/deneme/patient_file\yirmibes_resized_resized.jpg
[28 33 36 ... 96 82 63]
../keras/deneme/patient_file\yirmibir_resized_resized.jpg
[ 2 32 76 ...  1  1  1]
../keras/deneme/patient_file\yirmidokuz_resized_resized.jpg
[55 64 71 ... 77 50 40]
../keras/deneme/patient_file\yirmidort_resized_resized.jpg
[32 57 78

ValueError: Variable ConvNet/conv2d/kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "C:\Users\Isil\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1949, in __init__
    self._traceback = tf_stack.extract_stack()
  File "C:\Users\Isil\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3477, in _create_op_internal
    ret = Operation(
  File "C:\Users\Isil\anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 742, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "C:\Users\Isil\anaconda3\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 1752, in variable_v2
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "C:\Users\Isil\anaconda3\lib\site-packages\tensorflow\python\ops\state_ops.py", line 74, in variable_op_v2
    return gen_state_ops.variable_v2(
