In [97]:
from PIL import Image
import numpy as np
import sys
import os
import csv

# default format can be changed as needed
def createFileList(myDir, format='.jpg'):
    fileList = []
    print(myDir)
    for root, dirs, files in os.walk(myDir, topdown=False):
        for name in files:
            if name.endswith(format):
                fullName = os.path.join(root, name)
                fileList.append(fullName)
    return fileList

# load the original image
myFileList = createFileList('../keras/grayscale')

for file in myFileList:
    print(file)
    img_file = Image.open(file)
    # img_file.show()

    # get original image parameters...
    width, height = img_file.size
    format = img_file.format
    mode = img_file.mode

    # Make image Greyscale
    img_grey = img_file.convert('L')
    #img_grey.save('result.png')
    #img_grey.show()

    # Save Greyscale values
    value = np.asarray(img_grey.getdata(), dtype=np.int).reshape((img_grey.size[1], img_grey.size[0]))
    value = value.flatten()
    print(value)
    with open("KidneyDataset.csv", 'a',newline='') as f:
        writer = csv.writer(f)
        writer.writerow(value)

../keras/grayscale
../keras/grayscale\healthy\altmisdokuz_resized.jpg
[ 0  3  4 ... 38 31 20]
../keras/grayscale\healthy\altmisdort_resized.jpg
[ 0  2  4 ... 40 38 45]
../keras/grayscale\healthy\elliiki_resized.jpg
[ 3  1  6 ... 53 48 10]
../keras/grayscale\healthy\elliuc_resized.jpg
[ 0  2  2 ... 21 20 19]
../keras/grayscale\healthy\elliyedi_resized.jpg
[103 122 142 ...   9   9   1]
../keras/grayscale\healthy\kirkdokuz_resized.jpg
[ 1  2  4 ... 75 68 51]
../keras/grayscale\healthy\kirkuc_resized.jpg
[ 9 20 25 ... 89 62 54]
../keras/grayscale\healthy\onyedi_resized.jpg
[60 64 57 ... 23 24 25]
../keras/grayscale\healthy\on_resized.jpg
[ 1  5 13 ... 43 24 16]
../keras/grayscale\healthy\otuzsekiz_resized.jpg
[38 50 50 ...  4  0  0]
../keras/grayscale\healthy\sekiz_resized.jpg
[ 90 104 120 ...   3   2   5]
../keras/grayscale\patient\alti_resized.jpg
[208 211 213 ...  20  13   6]
../keras/grayscale\patient\altmisalti_resized.jpg
[ 4  4  4 ...  9  9 12]
../keras/grayscale\patient\altmisbes_r

ValueError: Variable ConvNet/conv2d/kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "C:\Users\Isil\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1949, in __init__
    self._traceback = tf_stack.extract_stack()
  File "C:\Users\Isil\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3477, in _create_op_internal
    ret = Operation(
  File "C:\Users\Isil\anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 742, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "C:\Users\Isil\anaconda3\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 1752, in variable_v2
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "C:\Users\Isil\anaconda3\lib\site-packages\tensorflow\python\ops\state_ops.py", line 74, in variable_op_v2
    return gen_state_ops.variable_v2(
